version: '2'
services:
  web:
    image: fpfis/httpd-php-dev:7.3
    working_dir: /var/www/html
    ports:
      - 8080:8080
    volumes:
      - .:/var/www/html
    environment:
      XDEBUG_CONFIG: "client_host=10.254.254.254 client_port=9000"
      XDEBUG_MODE: "debug"
      XDEBUG_SESSION: "PHPSTORM"
      XDEBUG_SESSION_START: "PHPSTORM"
      XDEBUG_TRIGGER: "PHPSTORM"
      PHP_IDE_CONFIG: "serverName=Docker"
      # For Xdebug setup, run this command in the terminal:
      # For Mac users: sudo ifconfig en0 alias 10.254.254.254 255.255.255.0
      # For Linux users: sudo ip addr add 10.254.254.254/32 dev lo label lo:1
